---
packages:
  - nginx
  - python3
  - python3-venv
  - python3-pip

apt_cache_valid_time: 3600 # 1 година

app_dir: /opt/flask-app
app_file: application.py # Нова назва файлу програми
app_port: 8080
