---
# Приклад використання: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html#examples
# необхідно зробити daemon reload
- name: Reload systemd
  systemd:
    daemon_reload: yes

# Приклад використання: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html#examples
- name: Restart flask_app
  systemd:
    name: flask_app
    state: restarted

# Приклад використання: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html#examples
- name: Restart nginx
  systemd:
    name: nginx
    state: restarted
